### ISSUE TITLE
Compatible issues - maybe 

### ISSUE THREAD

**Issue by awsumco** [tonsnoei/SolarmanWifiApi#1]
Try to get the test app to work with a Sunsynk/Deye Wifi Data Logger. From what I can tell it connects gets a response by the data is not correct as the message does not look right. Any suggestions would be helpful.

Here is the error we are getting 

Network request frame: reducted
InverterData: reducted
Length: 1
Message: �
================================ [Device Info] =================================

Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at SolarmanWifiApi.services.Models.SolarmanResponseFrame.GetString(Int32 offset, Int32 length) in /home/pi/ryan/SolarmanWifiApi/SolarmanWiFiApi/services/Models/SolarmanResponseFrame.cs:line 97
   at SolarmanWifiApi.services.Models.SolarmanResponseFrame.get_InverterId() in /home/pi/ryan/SolarmanWifiApi/SolarmanWiFiApi/services/Models/SolarmanResponseFrame.cs:line 20
   at SolarmanWifiTestConsole.Program.Main(String[] args) in /home/pi/ryan/SolarmanWifiApi/SolarmanWifiTestConsole/Program.cs:line 28

**Comment by tomislavravic** [comment]
I'm getting a similar issue. When I call the getInverterData(), the response takes a few seconds and only returns 14 bytes. Do you have some documentation that you could share? I would like to see if maybe there is a different header or command code to send?

**Comment by crudler** [comment]
Same issue here. Would love to know if this has been resolved by anyone

> Try to get the test app to work with a Sunsynk/Deye Wifi Data Logger. From what I can tell it connects gets a response by the data is not correct as the message does not look right. Any suggestions would be helpful.
> 
> Here is the error we are getting
> 
> Network request frame: reducted InverterData: reducted Length: 1 Message: � ================================ [Device Info] =================================
> 
> Unhandled Exception: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count) at SolarmanWifiApi.services.Models.SolarmanResponseFrame.GetString(Int32 offset, Int32 length) in /home/pi/ryan/SolarmanWifiApi/SolarmanWiFiApi/services/Models/SolarmanResponseFrame.cs:line 97 at SolarmanWifiApi.services.Models.SolarmanResponseFrame.get_InverterId() in /home/pi/ryan/SolarmanWifiApi/SolarmanWiFiApi/services/Models/SolarmanResponseFrame.cs:line 20 at SolarmanWifiTestConsole.Program.Main(String[] args) in /home/pi/ryan/SolarmanWifiApi/SolarmanWifiTestConsole/Program.cs:line 28
